# start of Meshtastic configure yaml
# channel_url: https://www.meshtastic.org/e/#CgMiAQESAjgD

# 1.3.29
config:
  bluetooth: {}
    # enabled: null
    # fixed_pin: null
    # mode: null
  device:
    role: ROUTER_CLIENT
    # debug_log_enabled: null
    # factory_reset: null
    # ntp_server: null
    # role: null
    # serial_enabled: null
  display: {}
    # auto_screen_carousel_secs: null
    # compass_north_top: null
    # gps_format: null
    # screen_on_secs: null
  lora: {}
    # bandwidth: null
    # coding_rate: null
    # frequency_offset: null
    # hop_limit: null
    # ignore_incoming: null
    # modem_preset: null
    # region: null
    # spread_factor: null
    # tx_disabled: null
    # tx_power: null
    # use_preset: null
  position: {}
    # fixed_position: null
    # gps_attempt_time: null
    # gps_disabled: null
    # gps_update_interval: null
    # position_broadcast_secs: null
    # position_broadcast_smart_disabled: null
    # position_flags: null
  power: {}
    # adc_multiplier_override: null
    # charge_current: null
    # is_power_saving: null
    # ls_secs: null
    # mesh_sds_timeout_secs: null
    # min_wake_secs: null
    # on_battery_shutdown_after_secs: null
    # sds_secs: null
    # wait_bluetooth_secs: null
  wifi: {}
    # enabled: null
    # mode: null
    # psk: null
    # ssid: null
modules:
  canned_message: {}
    # allow_input_source: null
    # enabled: null
    # inputbroker_event_ccw: null
    # inputbroker_event_cw: null
    # inputbroker_event_press: null
    # inputbroker_pin_a: null
    # inputbroker_pin_b: null
    # inputbroker_pin_press: null
    # rotary1_enabled: null
    # send_bell: null
    # updown1_enabled: null
  external_notification: {}
    # active: null
    # alert_bell: null
    # alert_message: null
    # enabled: null
    # output: null
    # output_ms: null
  mqtt: {}
    # address: null
    # enabled: null
    # encryption_enabled: null
    # json_enabled: null
    # password: null
    # username: null
  range_test: {}
    # enabled: null
    # save: null
    # sender: null
  serial: {}
    # baud: null
    # echo: null
    # enabled: null
    # mode: null
    # rxd: null
    # timeout: null
    # txd: null
  store_forward: {}
    # enabled: null
    # heartbeat: null
    # history_return_max: null
    # history_return_window: null
    # records: null
  telemetry: {}
    # device_update_interval: null
    # environment_display_fahrenheit: null
    # environment_measurement_enabled: null
    # environment_screen_enabled: null
    # environment_update_interval: null
node:
  owner: Meshtastic c430
  owner_short: c430
  # channels: null
  # owner: null
  # owner_short: null
